services:
    docker-test_adminer_1:
        name: Adminer
        url: "http://localhost:9000"
        description: An in browser database viewer
    wiki_db_1:
        name: Maria DB
        url: "http://localhost:9000"
    pi-server-manager_jenkins_1:
        name: Jenkins
        url: "http://localhost:8080"